// SPDX-License-Identifier: MPL-2.0

namespace RhoMicro.CodeAnalysis.Lyra;

using System;
using System.Buffers;
using System.Collections.Immutable;

/// <summary>
/// Provides options for the <see cref="CSharpSourceBuilder"/>.
/// </summary>
#if CSHARPSOURCEBUILDER_GENERATOR
[IncludeFile]
#endif
internal partial class CSharpSourceBuilderOptions
{
    /// <summary>
    /// Gets the default instance.
    /// </summary>
    public static CSharpSourceBuilderOptions Default { get; } = new();

    /// <summary>
    /// Gets the options to use when writing type names and no other options are explicitly provided.
    /// </summary>
    public virtual TypeNameOptions DefaultTypeNameOptions { get; init; } = TypeNameOptions.Default;
    
    /// <summary>
    /// Gets the initial indentation to apply to the builder.
    /// </summary>
    public virtual ImmutableArray<ReadOnlyMemory<Char>> InitialIndentation { get; init; } = [];

    /// <summary>
    /// Gets the indentation to apply when calling <see cref="CSharpSourceBuilder.Indent()"/>
    /// </summary>
    public virtual ReadOnlyMemory<Char> DefaultIndentation { get; init; } = "    ".AsMemory();

    /// <summary>
    /// Gets the newline character sequence to use when emitting a newline.
    /// </summary>
    public virtual ReadOnlyMemory<Char> Newline { get; init; } = "\n".AsMemory();

    /// <summary>
    /// Gets the <see cref="ArrayPool{T}"/> to use when creating buffers.
    /// </summary>
    public virtual ArrayPool<Char> CharBufferOwner { get; init; } = ArrayPool<Char>.Shared;

    /// <summary>
    /// Gets a callback to invoke before the first writing operation.
    /// </summary>
    public virtual Action<CSharpSourceBuilder, CancellationToken> Prelude { get; init; } =
        (w, _) => w.AppendLine(
                          $"""
                           // <auto-generated>
                           // This file was generated using the {typeof(CSharpSourceBuilder)}.
                           // </auto-generated>
                           """);

    /// <summary>
    /// Gets a value indicating if successive newlines are allowed.
    /// </summary>
    public virtual Boolean AllowConsecutiveEmptyLines { get; init; } = false;

    /// <summary>
    /// Gets the initial interpolation indentation detector.
    /// </summary>
    public virtual IInterpolationIndentationDetector InitialInterpolationIndentationDetector { get; init; } =
        new AggregateInterpolationIndentationDetector(
                WhitespaceInterpolationIndentationDetector.Instance,
                CommentInterpolationIndentationDetector.Instance);
}
