<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<developmentDependency>true</developmentDependency>
		<IsRoslynComponent>true</IsRoslynComponent>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageVersion>$(DebugAssemblyVersion)</PackageVersion>
		<PackageOutputPath>..\dist\dev</PackageOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<DefineConstants>$(DefineConstants);GENERATOR;RHOMICRO_CODEANALYSIS_UTILITYGENERATORS_DEV</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="bin\Debug\netstandard2.0\\RhoMicro.CodeAnalysis.UtilityGenerators.Dev.1.0.0.2490.dll" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="..\UtilityGenerators\README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
		<None Include="..\UtilityGenerators\LICENSE.txt" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../UtilityGenerators/UtilityGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<PackageReference Update="NETStandard.Library" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis" Version="4.12.0" />
		<PackageReference Include="PolySharp" Version="1.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<PropertyGroup>
		<PackageName>$(AssemblyName)</PackageName>
	</PropertyGroup>
	<PropertyGroup Condition=" $(Configuration) == 'Release' ">
		<PackageName>$(AssemblyNameWithoutVersion).$(PackageVersion)</PackageName>
	</PropertyGroup>
	
	<Target Name="MovePackageToDistDev" AfterTargets="GenerateNuspec">
		<Copy SourceFiles="$(PackageOutputPath)\$(PackageName).nupkg" DestinationFiles="$(PackageOutputPath)\..\dev\$(AssemblyNameWithoutVersion).1.0.0.nupkg" />
	</Target>

	<ItemGroup>
		<Compile Include="..\UtilityGenerators\AttributeFactory\AttributeFactoryGenerator.cs" Link="AttributeFactoryGenerator.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\AttributeFactoryModel.cs" Link="AttributeFactoryModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\Constants.cs" Link="Constants.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\ConstructorModel.cs" Link="ConstructorModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\InitializationMethodModel.cs" Link="InitializationMethodModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\InitializationMethodParameterModel.cs" Link="InitializationMethodParameterModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\InitializationMethodPipelineData.cs" Link="InitializationMethodPipelineData.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\ParameterMapping.cs" Link="ParameterMapping.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\ParameterModel.cs" Link="ParameterModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\PropertyModel.cs" Link="PropertyModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\SourceBuildingContext.cs" Link="SourceBuildingContext.cs" />
		<Compile Include="..\UtilityGenerators\FileInclusion\FileInclusionGenerator.cs" Link="FileInclusionGenerator.cs" />
		<Compile Include="..\UtilityGenerators\NonEquatable\NonEquatableGenerator.cs" Link="NonEquatableGenerator.cs" />
		<Compile Include="..\UtilityGenerators\Templating\AstStringBuilderVisitor.cs" Link="AstStringBuilderVisitor.cs" />
		<Compile Include="..\UtilityGenerators\Templating\BlockSyntax.cs" Link="BlockSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\BlockTerminators.cs" Link="BlockTerminators.cs" />
		<Compile Include="..\UtilityGenerators\Templating\CodeBlockSyntax.cs" Link="CodeBlockSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\CodeBodyChildSyntax.cs" Link="CodeBodyChildSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\CodeBodySyntax.cs" Link="CodeBodySyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\DebugTokenVerificationVisitor.cs" Link="DebugTokenVerificationVisitor.cs" />
		<Compile Include="..\UtilityGenerators\Templating\DefaultTokenVerificationVisitor.cs" Link="DefaultTokenVerificationVisitor.cs" />
		<Compile Include="..\UtilityGenerators\Templating\Diagnostic.cs" Link="Diagnostic.cs" />
		<Compile Include="..\UtilityGenerators\Templating\DiagnosticSeverity.cs" Link="DiagnosticSeverity.cs" />
		<Compile Include="..\UtilityGenerators\Templating\ISyntax.cs" Link="ISyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\Lexer.cs" Link="Lexer.cs" />
		<Compile Include="..\UtilityGenerators\Templating\Parser.cs" Link="Parser.cs" />
		<Compile Include="..\UtilityGenerators\Templating\ParseResult.cs" Link="ParseResult.cs" />
		<Compile Include="..\UtilityGenerators\Templating\ScanResult.cs" Link="ScanResult.cs" />
		<Compile Include="..\UtilityGenerators\Templating\SourcePosition.cs" Link="SourcePosition.cs" />
		<Compile Include="..\UtilityGenerators\Templating\SourceSpan.cs" Link="SourceSpan.cs" />
		<Compile Include="..\UtilityGenerators\Templating\SyntaxVisitor.cs" Link="SyntaxVisitor.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TemplateBlockSyntax.cs" Link="TemplateBlockSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TemplateChildSyntax.cs" Link="TemplateChildSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TemplateSpan.cs" Link="TemplateSpan.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TemplateString.cs" Link="TemplateString.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TemplateSyntax.cs" Link="TemplateSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TemplatingGenerator.cs" Link="TemplatingGenerator.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TextSyntax.cs" Link="TextSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\Token.cs" Link="Token.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TokenSpans.cs" Link="TokenSpans.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TokenType.cs" Link="TokenType.cs" />
		<Compile Include="..\UtilityGenerators\Templating\TokenVerificationVisitor.cs" Link="TokenVerificationVisitor.cs" />
		<Compile Include="..\UtilityGenerators\Templating\ValueBlockSyntax.cs" Link="ValueBlockSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\ValueBodySyntax.cs" Link="ValueBodySyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\ValueExpressionChildSyntax.cs" Link="ValueExpressionChildSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\ValueExpressionSyntax.cs" Link="ValueExpressionSyntax.cs" />
		<Compile Include="..\UtilityGenerators\Templating\ValueHeadSyntax.cs" Link="ValueHeadSyntax.cs" />
		<Compile Include="..\UtilityGenerators\TypeSymbolPattern\TypeSymbolPatternAttributeModel.cs" Link="TypeSymbolPatternAttributeModel.cs" />
		<Compile Include="..\UtilityGenerators\TypeSymbolPattern\TypeSymbolPatternGenerator.cs" Link="TypeSymbolPatternGenerator.cs" />
		<Compile Include="..\UtilityGenerators\TypeSymbolPattern\TypeSymbolPatternMethodModel.cs" Link="TypeSymbolPatternMethodModel.cs" />
		<Compile Include="..\UtilityGenerators\TypeSymbolPattern\TypeSymbolPatternMethodsModel.cs" Link="TypeSymbolPatternMethodsModel.cs" />
		<Compile Include="..\UtilityGenerators\TypeSymbolPattern\TypeSymbolPatternMethodsPartialModel.cs" Link="TypeSymbolPatternMethodsPartialModel.cs" />
	</ItemGroup>

</Project>
