<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<developmentDependency>true</developmentDependency>
		<IsRoslynComponent>true</IsRoslynComponent>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageVersion>$(DebugAssemblyVersion)</PackageVersion>
		<PackageOutputPath>..\dist\dev</PackageOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<DefineConstants>$(DefineConstants);GENERATOR;RHOMICRO_CODEANALYSIS_UTILITYGENERATORS_DEV</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="bin\Debug\netstandard2.0\\RhoMicro.CodeAnalysis.UtilityGenerators.Dev.1.0.0.2107.dll" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="..\UtilityGenerators\README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
		<None Include="..\UtilityGenerators\LICENSE.txt" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../UtilityGenerators/UtilityGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<PackageReference Update="NETStandard.Library" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis" Version="4.12.0" />
		<PackageReference Include="PolySharp" Version="1.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<PropertyGroup>
		<PackageName>$(AssemblyName)</PackageName>
	</PropertyGroup>
	<PropertyGroup Condition=" $(Configuration) == 'Release' ">
		<PackageName>$(AssemblyNameWithoutVersion).$(PackageVersion)</PackageName>
	</PropertyGroup>
	
	<Target Name="MovePackageToDistDev" AfterTargets="GenerateNuspec">
		<Copy SourceFiles="$(PackageOutputPath)\$(PackageName).nupkg" DestinationFiles="$(PackageOutputPath)\..\dev\$(AssemblyNameWithoutVersion).1.0.0.nupkg" />
	</Target>

	<ItemGroup>
		<Compile Include="..\UtilityGenerators\AttributeFactory\AttributeFactoryGenerator.cs" Link="AttributeFactoryGenerator.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\AttributeFactoryModel.cs" Link="AttributeFactoryModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\Constants.cs" Link="Constants.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\ConstructorModel.cs" Link="ConstructorModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\InitializationMethodModel.cs" Link="InitializationMethodModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\InitializationMethodParameterModel.cs" Link="InitializationMethodParameterModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\InitializationMethodPipelineData.cs" Link="InitializationMethodPipelineData.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\ParameterMapping.cs" Link="ParameterMapping.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\ParameterModel.cs" Link="ParameterModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\PropertyModel.cs" Link="PropertyModel.cs" />
		<Compile Include="..\UtilityGenerators\AttributeFactory\SourceBuildingContext.cs" Link="SourceBuildingContext.cs" />
		<Compile Include="..\UtilityGenerators\FileInclusion\FileInclusionGenerator.cs" Link="FileInclusionGenerator.cs" />
		<Compile Include="..\UtilityGenerators\NonEquatable\NonEquatableGenerator.cs" Link="NonEquatableGenerator.cs" />
	</ItemGroup>

</Project>
