namespace RhoMicro.CodeAnalysis.Equa;

using System.Collections.Immutable;
using System.Runtime.InteropServices;
using Generated;
using Library.Models;
using Lyra;
using Microsoft.CodeAnalysis;

/// <summary>
/// Generates collection aware value equality implementations for <see cref="Object.Equals(Object)"/>
/// and <see cref="Object.GetHashCode"/>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed partial class Generator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat _namespaceFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces);

    private static readonly CSharpSourceBuilderOptions _sourceBuilderOptions = new()
    {
        Prelude = static (b, ct) =>
        {
            ct.ThrowIfCancellationRequested();

            b.AppendLine(
                $"""
                 // <auto-generated>
                 // This file was generated using the Equa source generator.
                 // SPDX-License-Identifier: MPL-2.0
                 // </auto-generated>
                 """);
        }
    };

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
                typeof(ValueEqualityAttribute).FullName,
                static (n, ct) =>
                {
                    ct.ThrowIfCancellationRequested();

                    return true;
                }, static (ctx, ct) =>
                {
                    ct.ThrowIfCancellationRequested();

                    if (ctx.TargetSymbol is not { ContainingType: { } target })
                    {
                        return null;
                    }

                    using var collections = ModelCreationContext.CreateDefault(ct);
                    
                    var containingTypes = collections.CollectionFactory.CreateList<ContainingTypeModel>();
                    if (target.ContainingType is { } t)
                    {
                        appendContainingType(t);
                    }

                    var @namespace = target.ContainingNamespace.ToDisplayString(_namespaceFormat) ?? String.Empty;
                    var typeParameters = collections.CollectionFactory.CreateList<String>();
                    var vectorMembers = collections.CollectionFactory.CreateList<MemberModel>();
                    var scalarMembers = collections.CollectionFactory.CreateList<MemberModel>();

                    for (var i = 0; i < target.TypeParameters.Length; i++)
                    {
                        ct.ThrowIfCancellationRequested();

                        typeParameters[i] = target.TypeParameters[i].Name;
                    }

                    foreach (var member in target.GetMembers())
                    {
                        ct.ThrowIfCancellationRequested();

                        if (member is not
                            {
                                CanBeReferencedByName: true,
                                Kind: SymbolKind.Property or SymbolKind.Field,
                                IsStatic: false
                            })
                        {
                            continue;
                        }

                        var memberType = member switch
                        {
                            IFieldSymbol f => f.Type,
                            IPropertySymbol p => p.Type,
                            _ => null
                        };

                        if (memberType is null)
                        {
                            continue;
                        }

                        var memberModel = new MemberModel(
                            Type: memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                            Name: member.Name);

                        if (ImplementsIEnumerable(memberType, ct))
                        {
                            vectorMembers.Add(memberModel);
                        }
                        else
                        {
                            scalarMembers.Add(memberModel);
                        }
                    }

                    var result = new RecordModel(
                        target.TypeKind,
                        target.IsRecord,
                        target.Name,
                        @namespace,
                        typeParameters,
                        containingTypes,
                        vectorMembers,
                        scalarMembers);

                    return result;

                    void appendContainingType(INamedTypeSymbol type)
                    {
                        if (type.ContainingType is { } t)
                        {
                            appendContainingType(t);
                        }

                        var typeParameters = new String[type.Arity];

                        for (var i = 0; i < type.TypeParameters.Length; i++)
                        {
                            ct.ThrowIfCancellationRequested();

                            typeParameters[i] = type.TypeParameters[i].Name;
                        }

                        var containingType = new ContainingTypeModel(
                            $"{(type.IsRecord ? "record " : String.Empty)}{(type.TypeKind is TypeKind.Struct ? "struct" : "class")}",
                            type.Name,
                            ImmutableCollectionsMarshal.AsImmutableArray(typeParameters));

                        containingTypes.Add(containingType);
                    }
                })!
            .Where<RecordModel>(m => m is not null)
            .Select(static (m, ct) =>
            {
                ct.ThrowIfCancellationRequested();

                var builder = new CSharpSourceBuilder(_sourceBuilderOptions).SetCancellationToken(ct);

                var hintName = builder
                    .SetCondition(m.Namespace is not [])
                    .Append($"{m.Namespace}.")
                    .UnsetCondition()
                    .Append(m.Name)
                    .SetCondition(m.TypeParameters is not [])
                    .Append($"`{m.TypeParameters.Count}")
                    .UnsetCondition()
                    .Append(".g.cs")
                    .ToString();

                var source = builder.Clear().Append(new RecordComponent(m)).ToString();

                return (hintName, source);
            });

        context.RegisterSourceOutput(sourceProvider, static (ctx, t) => ctx.AddSource(t.hintName, t.source));
        IncludedFileSources.RegisterToContext(context);
    }

    private static Boolean ImplementsIEnumerable(ITypeSymbol type, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        foreach (var @interface in type.AllInterfaces)
        {
            ct.ThrowIfCancellationRequested();

            var isIEnumerable = @interface is
            {
                TypeKind: TypeKind.Interface,
                Name: nameof(IEnumerable<>),
                TypeArguments: [{ }],
                ContainingNamespace:
                {
                    Name: "Generic",
                    ContainingNamespace:
                    {
                        Name: "Collections",
                        ContainingNamespace:
                        {
                            Name: "System",
                            ContainingNamespace:
                            {
                                IsGlobalNamespace: true
                            }
                        }
                    }
                }
            };

            if (isIEnumerable)
            {
                return true;
            }
        }

        return false;
    }
}
