namespace RhoMicro.CodeAnalysis.UtilityGenerators.Tests;

using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using Basic.Reference.Assemblies;

[AttributeUsage(AttributeTargets.Class)]
internal sealed class UtilityGeneratorTestAssertion : Attribute;

public abstract class TestBase<TGenerator>
    where TGenerator : IIncrementalGenerator, new()
{
    protected TestBase() : this(Net80.References.All.ToArray()) { }
    protected TestBase(IEnumerable<MetadataReference> references) =>
        _references = [.. references];

    private readonly MetadataReference[] _references;

    //requiring >= C#11 due to file scoped modifiers
    private const LanguageVersion _targetLanguageVersion = LanguageVersion.Preview;
    private static readonly CSharpParseOptions _parseOptions =
        new(languageVersion: _targetLanguageVersion,
            documentationMode: DocumentationMode.Diagnose,
            kind: SourceCodeKind.Regular);

    protected void TestFactory(String source, String assertion)
    {
        Compilation compilation = CreateCompilation(source, assertion);
        var runResult = RunGenerator(ref compilation);
        Assert.Empty(runResult.Diagnostics.Where(d => d.IsWarningAsError || d.Severity is DiagnosticSeverity.Error));

    }
    protected GeneratorDriverRunResult RunGenerator(ref Compilation compilation)
    {
        var generator = new TGenerator();

        var driver = CSharpGeneratorDriver.Create(generator)
            .WithUpdatedParseOptions(_parseOptions);

        // Run the generation pass
        // (Note: the generator driver itself is immutable, and all calls return an updated version of the driver that you should use for subsequent calls)
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out compilation, out var diagnostics);

        if(!diagnostics.IsEmpty)
            Assert.Fail("Generator produced diagnostics.");

        var aggregateDiagnostics = compilation
            .GetDiagnostics()
            .Where(d => d is { IsWarningAsError: true } or { Severity: DiagnosticSeverity.Error });

        if(aggregateDiagnostics.Any())
            Assert.Fail("Compilation with generated sources produced diagnostics.");

        // Or we can look at the results directly:
        var result = driver.GetRunResult();

        if(!result.Diagnostics.IsEmpty)
            Assert.Fail("Generator run result contains diagnostics.");

        return result;
    }

    protected CSharpCompilation CreateCompilation(params String[] sources)
    {
        var options = CreateCompilationOptions();
        var syntaxTrees = sources
            .Append(
            """
            namespace RhoMicro.CodeAnalysis.UtilityGenerators.Tests;
            [AttributeUsage(AttributeTargets.Class)]
            internal sealed class UtilityGeneratorTestAssertion : Attribute;
            """
            )
            .Append(
            """
            // <auto-generated/>
            #pragma warning disable
            #nullable enable annotations

            // Licensed to the .NET Foundation under one or more agreements.
            // The .NET Foundation licenses this file to you under the MIT license.

            namespace System.Diagnostics.CodeAnalysis
            {
                /// <summary>
                /// Specifies that when a method returns <see cref="ReturnValue"/>, the parameter will not be null even if the corresponding type allows it.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, Inherited = false)]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal sealed class NotNullWhenAttribute : global::System.Attribute
                {
                    /// <summary>
                    /// Initializes the attribute with the specified return value condition.
                    /// </summary>
                    /// <param name="returnValue">The return value condition. If the method returns this value, the associated parameter will not be null.</param>
                    public NotNullWhenAttribute(bool returnValue)
                    {
                        ReturnValue = returnValue;
                    }

                    /// <summary>Gets the return value condition.</summary>
                    public bool ReturnValue { get; }
                }
                [global::System.AttributeUsage(
                    global::System.AttributeTargets.Method |
                    global::System.AttributeTargets.Property,
                    Inherited = false, AllowMultiple = true)]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal sealed class MemberNotNullWhenAttribute : global::System.Attribute
                {
                    /// <summary>
                    /// Initializes the attribute with the specified return value condition and a field or property member.
                    /// </summary>
                    /// <param name="returnValue">The return value condition. If the method returns this value, the associated parameter will not be null.</param>
                    /// <param name="member">The field or property member that is promised to be not-null.</param>
                    public MemberNotNullWhenAttribute(bool returnValue, string member)
                    {
                        ReturnValue = returnValue;
                        Members = new[] { member };
                    }

                    /// <summary>
                    /// Initializes the attribute with the specified return value condition and list of field and property members.
                    /// </summary>
                    /// <param name="returnValue">The return value condition. If the method returns this value, the associated parameter will not be null.</param>
                    /// <param name="members">The list of field and property members that are promised to be not-null.</param>
                    public MemberNotNullWhenAttribute(bool returnValue, params string[] members)
                    {
                        ReturnValue = returnValue;
                        Members = members;
                    }

                    /// <summary>
                    /// Gets the return value condition.
                    /// </summary>
                    public bool ReturnValue { get; }

                    /// <summary>
                    /// Gets field or property member names.
                    /// </summary>
                    public string[] Members { get; }
                }
            }
            """)
            .Select(s => CSharpSyntaxTree.ParseText(s, _parseOptions));

        var result = CSharpCompilation.Create(
            assemblyName: $"TestAssembly_{Interlocked.Increment(ref _testAssemblyCount)}",
            syntaxTrees: syntaxTrees,
            references: [.. _references],
            options: options);

        return result;
    }
    private static Int32 _testAssemblyCount;
    private static CSharpCompilationOptions CreateCompilationOptions()
    {
        String[] args = ["/warnaserror"];
#pragma warning disable RS1035 // Do not use APIs banned for analyzers (not an analyzer)
        var commandLineArguments = CSharpCommandLineParser.Default.Parse(args, baseDirectory: Environment.CurrentDirectory, sdkDirectory: Environment.CurrentDirectory);
#pragma warning restore RS1035 // Do not use APIs banned for analyzers
        var result = commandLineArguments.CompilationOptions
            .WithOutputKind(OutputKind.DynamicallyLinkedLibrary);

        return result;
    }
}
