// <auto-generated>
// This file has been auto generated using the RhoMicro.CodeAnalysis.AttributeFactoryGenerator.
// </auto-generated>
#nullable enable
#pragma warning disable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace RhoMicro.CodeAnalysis
{
    internal partial class GeneratedJsonSchemaAttribute
    {
        /// <summary>
        /// Attempts to create an instance of <see cref = "GeneratedJsonSchemaAttribute"/> based on an 
        /// instance of <see cref = "AttributeData"/>.
        /// </summary>
        /// <param name = "data">The attribute data to try and create an instance from.</param>
        /// <param name = "result">
        /// Will contain the created instance, if one could be created; otherwise, <see langword="null"/>.
        /// </param>
        /// <returns>
        /// <see langword="true"/> if an instance could be created; otherwise, <see langword="false"/>.
        /// </returns>
        public static Boolean TryCreate(AttributeData data, out GeneratedJsonSchemaAttribute? result)
        {
            result = null;
            if(data.AttributeClass == null 
                || data.AttributeClass.MetadataName != "GeneratedJsonSchemaAttribute" 
                || data.AttributeClass.ContainingNamespace.ToDisplayString() != "RhoMicro.CodeAnalysis")
            {
                return false;
            }

            var ctorArgs = data.ConstructorArguments;
            switch(ctorArgs.Length)
            {
                case 1:
                    if(( ctorArgs[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGenericsOptions((SymbolDisplayGenericsOptions)5)) == "string" || false ))
                    {
                        var arg0 = ctorArgs[0].IsNull ? default : (string)ctorArgs[0].Value;
                        result = new GeneratedJsonSchemaAttribute(schema: arg0);
                    } else
                    {
                        return false;
                    }

                    break;
                default:
                    return false;
            }

            var propArgs = data.NamedArguments;
            foreach(var propArg in propArgs)
            {
                switch(propArg.Key)
                {
                    default:
                        return false;
                }
            }

            return true;
            static Object[] getValues(TypedConstant constant) => constant.Value != null ? new Object[]
            {
                constant.Value
            }

            : constant.IsNull ? null : constant.Values.Select(getValues).ToArray();
        }

        public const String MetadataName = "RhoMicro.CodeAnalysis.GeneratedJsonSchemaAttribute";
        public const String SourceText = """
#pragma warning disable
namespace RhoMicro.CodeAnalysis;
using System;

/// <summary>
/// Provides access to generated json schemata for use by other tools.
/// </summary>
[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
#if GENERATOR
[GenerateFactory]
[IncludeFile]
#endif
internal sealed partial class GeneratedJsonSchemaAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    /// <param name="schema">
    /// The generated schema.
    /// </param>
    public GeneratedJsonSchemaAttribute(String schema) => Schema = schema;
    /// <summary>
    /// Gets the generated schema.
    /// </summary>
    public String Schema { get; }
}
""";
    }

    /// <summary>
    /// Contains extension methods pertaining to the <see cref = "GeneratedJsonSchemaAttribute"/> type.
    /// </summary>
    internal static class GeneratedJsonSchemaAttributeExtensions
    {
        /// <summary>
        /// Filters and projects an enumeration of <see cref = "AttributeData"/> onto 
        /// instances of <see cref = "GeneratedJsonSchemaAttribute"/>.
        /// </summary>
        /// <param name = "data">The attribute data to filter.</param>
        /// <returns>The filtered and projected data.</returns>
        public static IEnumerable<GeneratedJsonSchemaAttribute> OfGeneratedJsonSchemaAttribute(this IEnumerable<AttributeData> data) => data.Select(d => (Success: GeneratedJsonSchemaAttribute.TryCreate(d, out var a), Attribute: a)).Where(t => t.Success).Select(t => t.Attribute);
        /// <summary>
        /// Attempts to retrieve the first instance of <see cref = "GeneratedJsonSchemaAttribute"/> from a symbol.
        /// </summary>
        /// <param name = "symbol">The symbol whose attributes to scan for an instance of <see cref = "GeneratedJsonSchemaAttribute"/>.</param>
        /// <param name = "attribute">The attribute retrieved, if one could be located; otherwise, <see langword="null"/>.</param>
        public static Boolean TryGetFirstGeneratedJsonSchemaAttribute(this ISymbol symbol, out GeneratedJsonSchemaAttribute attribute)
        {
            attribute = symbol.GetAttributes().OfGeneratedJsonSchemaAttribute().FirstOrDefault();
            return attribute != null;
        }

        public static IncrementalValuesProvider<T> ForGeneratedJsonSchemaAttribute<T>(this SyntaxValueProvider provider, Func<SyntaxNode, CancellationToken, bool> predicate, Func<GeneratorAttributeSyntaxContext, CancellationToken, T> transform) => provider.ForAttributeWithMetadataName("RhoMicro.CodeAnalysis.GeneratedJsonSchemaAttribute", predicate, transform);
    }
}