// <auto-generated>
// This file has been auto generated using the RhoMicro.CodeAnalysis.AttributeFactoryGenerator.
// </auto-generated>
#nullable enable
#pragma warning disable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace RhoMicro.CodeAnalysis
{
    internal partial class JsonSchemaAttribute
    {
        /// <summary>
        /// Attempts to create an instance of <see cref = "JsonSchemaAttribute"/> based on an 
        /// instance of <see cref = "AttributeData"/>.
        /// </summary>
        /// <param name = "data">The attribute data to try and create an instance from.</param>
        /// <param name = "result">
        /// Will contain the created instance, if one could be created; otherwise, <see langword="null"/>.
        /// </param>
        /// <returns>
        /// <see langword="true"/> if an instance could be created; otherwise, <see langword="false"/>.
        /// </returns>
        public static Boolean TryCreate(AttributeData data, out JsonSchemaAttribute? result)
        {
            result = null;
            if(data.AttributeClass == null 
                || data.AttributeClass.MetadataName != "JsonSchemaAttribute" 
                || data.AttributeClass.ContainingNamespace.ToDisplayString() != "RhoMicro.CodeAnalysis")
            {
                return false;
            }

            var ctorArgs = data.ConstructorArguments;
            switch(ctorArgs.Length)
            {
                case 0:
                    result = new JsonSchemaAttribute();
                    break;
                default:
                    return false;
            }

            var propArgs = data.NamedArguments;
            foreach(var propArg in propArgs)
            {
                switch(propArg.Key)
                {
                    case "Id":
                        try
                        {
                            result.Id = (string)propArg.Value.Value;
                        } catch
                        {
                        }

                        break;
                    case "Title":
                        try
                        {
                            result.Title = (string)propArg.Value.Value;
                        } catch
                        {
                        }

                        break;
                    case "Description":
                        try
                        {
                            result.Description = (string)propArg.Value.Value;
                        } catch
                        {
                        }

                        break;
                    default:
                        return false;
                }
            }

            return true;
            static Object[] getValues(TypedConstant constant) => constant.Value != null ? new Object[]
            {
                constant.Value
            }

            : constant.IsNull ? null : constant.Values.Select(getValues).ToArray();
        }

        public const String MetadataName = "RhoMicro.CodeAnalysis.JsonSchemaAttribute";
        public const String SourceText = """
#pragma warning disable
namespace RhoMicro.CodeAnalysis;
using System;

/// <summary>
/// Marks the targeted type for json schema generation.
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
#if GENERATOR
[GenerateFactory]
[IncludeFile]
#endif
internal sealed partial class JsonSchemaAttribute : Attribute
{
    /// <summary>
    /// Gets or sets the json schema id of the generated schema. If left empty
    /// or set to <see langword="null"/>, a schema id will be generated based on
    /// the annotated type.
    /// </summary>
    public String? Id { get; set; }
    /// <summary>
    /// Gets or sets the title of the schema.
    /// </summary>
    public String Title { get; set; } = String.Empty;
    /// <summary>
    /// Gets or sets the description of the schema.
    /// </summary>
    public String Description { get; set; } = String.Empty;
}

""";
    }

    /// <summary>
    /// Contains extension methods pertaining to the <see cref = "JsonSchemaAttribute"/> type.
    /// </summary>
    internal static class JsonSchemaAttributeExtensions
    {
        /// <summary>
        /// Filters and projects an enumeration of <see cref = "AttributeData"/> onto 
        /// instances of <see cref = "JsonSchemaAttribute"/>.
        /// </summary>
        /// <param name = "data">The attribute data to filter.</param>
        /// <returns>The filtered and projected data.</returns>
        public static IEnumerable<JsonSchemaAttribute> OfJsonSchemaAttribute(this IEnumerable<AttributeData> data) => data.Select(d => (Success: JsonSchemaAttribute.TryCreate(d, out var a), Attribute: a)).Where(t => t.Success).Select(t => t.Attribute);
        /// <summary>
        /// Attempts to retrieve the first instance of <see cref = "JsonSchemaAttribute"/> from a symbol.
        /// </summary>
        /// <param name = "symbol">The symbol whose attributes to scan for an instance of <see cref = "JsonSchemaAttribute"/>.</param>
        /// <param name = "attribute">The attribute retrieved, if one could be located; otherwise, <see langword="null"/>.</param>
        public static Boolean TryGetFirstJsonSchemaAttribute(this ISymbol symbol, out JsonSchemaAttribute attribute)
        {
            attribute = symbol.GetAttributes().OfJsonSchemaAttribute().FirstOrDefault();
            return attribute != null;
        }

        public static IncrementalValuesProvider<T> ForJsonSchemaAttribute<T>(this SyntaxValueProvider provider, Func<SyntaxNode, CancellationToken, bool> predicate, Func<GeneratorAttributeSyntaxContext, CancellationToken, T> transform) => provider.ForAttributeWithMetadataName("RhoMicro.CodeAnalysis.JsonSchemaAttribute", predicate, transform);
    }
}