<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<developmentDependency>true</developmentDependency>
		<NoPackageAnalysis>true</NoPackageAnalysis>
		<IsRoslynComponent>true</IsRoslynComponent>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>Generates options pattern implementations for interfaces and hides the option pattern from consumers.</Description>
		<PackageTags>Source Generator;options;option pattern;</PackageTags>
		<!--<PackageIcon>logo_256.png</PackageIcon>-->
	</PropertyGroup>

	<PropertyGroup>
		<DefineConstants>$(DefineConstants);GENERATOR;RHOMICRO_CODEANALYSIS_OPTIONSGENERATOR</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Update="NETStandard.Library" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
		<PackageReference Include="PolySharp" Version="1.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="RhoMicro.CodeAnalysis.UtilityGenerators" Version="20.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<!--<None Include="docs\logo_256.png" Pack="true" PackagePath="" />-->
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
	</ItemGroup>

</Project>
