// SPDX-License-Identifier: MPL-2.0

namespace RhoMicro.CodeAnalysis.Janus;

using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.InteropServices;
using Generated;
using Library.Models;
using Library.Models.Collections;
using Lyra;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

/// <summary>
/// Generates union type implementations.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class JanusGenerator : IIncrementalGenerator
{
    private static readonly ImmutableArray<String> _genericUnionTypeAttributeMetadataNames =
    [
        typeof(UnionTypeAttribute<>).FullName,
        typeof(UnionTypeAttribute<,>).FullName,
        typeof(UnionTypeAttribute<,,>).FullName,
        typeof(UnionTypeAttribute<,,,>).FullName,
        typeof(UnionTypeAttribute<,,,,>).FullName,
        typeof(UnionTypeAttribute<,,,,,>).FullName,
        typeof(UnionTypeAttribute<,,,,,,>).FullName,
        typeof(UnionTypeAttribute<,,,,,,,>).FullName
    ];

    private static readonly CSharpSourceBuilderOptions _sourceBuilderOptions = new()
    {
        Prelude = static (b, ct) =>
        {
            ct.ThrowIfCancellationRequested();

            b.AppendLine(
                $"""
                 // <auto-generated>
                 // This file was generated using the Janus source generator.
                 // SPDX-License-Identifier: MPL-2.0
                 // </auto-generated>
                 #nullable enable
                 """);
        }
    };

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var defaultSettingsProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName<UnionTypeSettingsAttribute.Model?>(
                typeof(UnionTypeSettingsAttribute).FullName!,
                static (n, ct) =>
                {
                    ct.ThrowIfCancellationRequested();

                    var result = n is CompilationUnitSyntax;

                    return result;
                }, static (ctx, ct) =>
                {
                    ct.ThrowIfCancellationRequested();

                    if (!ctx.Attributes[0]
                        .TryGetUnionTypeSettingsAttributeModel(out var settings, cancellationToken: ct))
                    {
                        return null;
                    }

                    return settings;
                })
            .Collect()
            .Select(static (s, ct) =>
            {
                ct.ThrowIfCancellationRequested();

                if (s is not [{ } settings, ..])
                {
                    return UnionTypeSettingsAttribute.Model.InheritanceRoot;
                }

                // settings are copied in collection expression above,
                // so we don't need to do that before mutating to
                // avoid cache corruption
                settings.Inherit(UnionTypeSettingsAttribute.Model.InheritanceRoot);
                return settings;
            });

        var aggregateUnionTypesProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
                typeof(UnionTypeAttribute).FullName!,
                static (n, ct) =>
                {
                    ct.ThrowIfCancellationRequested();

                    var result = n is TypeParameterSyntax;

                    return result;
                }, static (ctx, ct) =>
                {
                    ct.ThrowIfCancellationRequested();

                    var result = ctx.TargetSymbol is ITypeParameterSymbol { ContainingType: { } target } &&
                                 UnionModel.TryCreate(target, out var r, ct)
                        ? r
                        : null;

                    return result;
                })
            .Where(static m => m is not null)!
            .Collect<UnionModel>();

        for (var i = 0; i < 8; i++)
        {
            var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
                    _genericUnionTypeAttributeMetadataNames[i],
                    static (n, ct) =>
                    {
                        ct.ThrowIfCancellationRequested();

                        var result = n is TypeDeclarationSyntax;

                        return result;
                    }, static (ctx, ct) =>
                    {
                        ct.ThrowIfCancellationRequested();

                        var result = ctx.TargetSymbol is INamedTypeSymbol target &&
                                     UnionModel.TryCreate(target, out var r, ct)
                            ? r
                            : null;

                        return result;
                    })
                .Where(static m => m is not null)!
                .Collect<UnionModel>();

            aggregateUnionTypesProvider = aggregateUnionTypesProvider
                .Combine(provider)
                .Select(static (t, ct) =>
                {
                    ct.ThrowIfCancellationRequested();

                    var (left, right) = t;

                    ImmutableArray<UnionModel> result = [..left, ..right];

                    return result;
                })
                .WithComparer(ImmutableArrayEqualityComparer<UnionModel>.Default);
        }

        var sourceProvider = aggregateUnionTypesProvider
            .SelectMany(static (a, ct) =>
            {
                ct.ThrowIfCancellationRequested();

                var included = new HashSet<UnionModel>();

                foreach (var model in a)
                {
                    ct.ThrowIfCancellationRequested();

                    _ = included.Add(model);
                }

                return included;
            })
            .Combine(defaultSettingsProvider)
            .Select(static (t, ct) =>
            {
                var (union, defaultSettings) = t;

                // copy settings before mutating to avoid cache corruption
                var unionSettings = union.Settings;
                unionSettings.Inherit(defaultSettings);
                union = union with { Settings = unionSettings };

                var result = union.GetValidation(ct).HasUnsupportedSettingsAwareState
                    ? null
                    : union;

                return result;
            })!
            .Where<UnionModel>(m => m is not null)
            .Select(static (m, ct) =>
            {
                ct.ThrowIfCancellationRequested();

                var sourceBuilder = new CSharpSourceBuilder(_sourceBuilderOptions);
                var source = sourceBuilder
                    .SetCancellationToken(ct)
                    .Append(new UnionComponent(m))
                    .ToString();

                var hintName = sourceBuilder
                    .Clear()
                    .SkipPreludeChecks()
                    .Append(new UnionTypeMetadataNameComponent(m))
                    .Append(".g.cs")
                    .ToString();

                return (hintName, source);
            });

        context.RegisterSourceOutput(sourceProvider, static (ctx, t) => ctx.AddSource(t.hintName, t.source));
        IncludedFileSources.RegisterToContext(context);
    }
}
