// <auto-generated>
// SPDX-License-Identifier: MPL-2.0
// </auto-generated>
#nullable enable
#pragma warning disable

namespace RhoMicro.CodeAnalysis
{
    /// <summary>
    /// Defines settings for generating an implementation of <see cref="Object.ToString"/>.
    /// </summary>
    enum ToStringSetting
    {
        /// <summary>
        /// Inherits the setting. This is the default value.
        /// <list type="bullet">
        /// <item>If the target is a type, it will inherit the setting from its containing assembly.</item>
        /// <item>If the target is an assembly, the <see cref="Detailed"/> setting will be used.</item>
        /// </list>
        /// </summary>
        Inherit,
        /// <summary>
        /// The generator will emit an implementation that returns detailed information, including:
        /// <list type="bullet">
        /// <item><description>the name of the union type</description></item>
        /// <item><description>the set of variants</description></item>
        /// <item><description>an indication of which variant is being represented by the instance</description></item>
        /// <item><description>the value currently being represented by the instance</description></item>
        /// </list>
        /// </summary>
        Detailed,
        /// <summary>
        /// The generator will not generate an implementation of <see cref="Object.ToString"/>.
        /// </summary>
        None,
        /// <summary>
        /// The generator will generate an implementation that returns the result of calling <see cref="Object.ToString"/> on the currently represented value.
        /// </summary>
        Simple
    }

    /// <summary>
    /// Defines settings pertaining to equality operator implementations.
    /// </summary>
    enum EqualityOperatorsSetting
    {
        /// <summary>
        /// Inherits the setting. This is the default value.
        /// <list type="bullet">
        /// <item>If the target is a type, it will inherit the setting from its containing assembly.</item>
        /// <item>If the target is an assembly, the <see cref="EmitOperatorsIfValueType"/> setting will be used.</item>
        /// </list>
        /// </summary>
        Inherit,
        /// <summary>
        /// Equality operators will be emitted only if the target union type is a value type.
        /// </summary>
        EmitOperatorsIfValueType,
        /// <summary>
        /// Equality operators will be emitted.
        /// </summary>
        EmitOperators,
        /// <summary>
        /// Equality operators will be omitted.
        /// </summary>
        OmitOperators
    }

    /// <summary>
    /// Defiles settings pertaining to JSON converter implementations.
    /// </summary>
    enum JsonConverterSetting
    {
        /// <summary>
        /// Inherits the setting. This is the default value.
        /// <list type="bullet">
        /// <item>If the target is a type, it will inherit the setting from its containing assembly.</item>
        /// <item>If the target is an assembly, the <see cref="OmitJsonConverter"/> setting will be used.</item>
        /// </list>
        /// </summary>
        Inherit,
        /// <summary>
        /// No JSON converter implementation is emitted.
        /// </summary>
        OmitJsonConverter,
        /// <summary>
        /// A JSON converter implementation is emitted. 
        /// </summary>
        EmitJsonConverter
    }
    
    /// <summary>
    /// Supplies the generator with additional settings on how to generate a targeted union type.
    /// If the target member is an assembly, the attribute supplies default values for any union 
    /// type setting not defined.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class | global::System.AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
#if RHOMICRO_CODEANALYSIS_JANUS_ANALYZERS
    [global::RhoMicro.CodeAnalysis.IncludeFile]
    [RhoMicro.CodeAnalysis.GenerateFactory(GenerateModelTypeAsStruct = true)]
#endif
    sealed partial class UnionTypeSettingsAttribute : global::System.Attribute
    {
        /// <summary>
        /// Defines how to generate an implementation for <see cref="Object.ToString"/>.
        /// </summary>
        public ToStringSetting ToStringSetting { get; set; }
        
        /// <summary>
        /// Indicates how to generate equality operators.
        /// By default, equality operators will only be emitted for value types, to preserve
        /// reference equality for comparing reference union types via <c>==</c> or <c>!=</c>.
        /// </summary>
        public EqualityOperatorsSetting EqualityOperatorsSetting { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether to make the union type JSON serializable.
        /// </summary>
        /// <remarks>
        /// The generated JSON serialization support is not AOT-compatible.
        /// If you require this as a feature, please open an issue with the maintainer.
        /// </remarks>
        public JsonConverterSetting JsonConverterSetting { get; set; }

    }
}
