// <auto-generated>
// SPDX-License-Identifier: MPL-2.0
// </auto-generated>
#nullable enable
#pragma warning disable

namespace RhoMicro.CodeAnalysis
{
    /// <summary>
    /// Marks the target type as a union type.
    /// </summary>
    abstract class UnionTypeBaseAttribute : global::System.Attribute
    {
        /// <summary>
        /// Gets or sets the groups that the variant is to be a part of. 
        /// Variants that share a group may be checked for using e.g.:
        /// <c>myUnion.Variant.Groups.ContainsMyGroup</c> where <c>MyGroup</c>
        /// is the name of the group that the variant is a part of.
        /// </summary>
        public virtual string[] Groups { get; set; } = global::System.Array.Empty<string>();
    }

    /// <summary>
    /// Marks the target type as a union type.
    /// </summary>
    abstract class NamedUnionTypeBaseAttribute : UnionTypeBaseAttribute
    {
        /// <summary>
        /// Gets or sets the name to use for members representing the variant of the union.
        /// For example, the variant <see cref="List{T}"/> would be represented using names like
        /// <c>List_of_T</c>. Setting this property to <c>MyName</c> will instruct the generator to use
        /// member names like <c>MyName</c> instead of <c>List_of_T</c>. Use this property to avoid
        /// name collisions in generated code. Since the name will be used for member names, it is
        /// required to also be a valid C# identifier.
        /// </summary>
        public virtual string? Name { get; set; }
        
        /// <summary>
        /// Gets or sets the description of the variant.
        /// This value will be used in documentation comments, so escaping special characters might be necessary.
        /// </summary>
        public virtual string? Description { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether to generate the reference type variant as nullable.
        /// This setting is only relevant for reference types or generic type parameters not constrained
        /// to <see langword="struct"/>. In order to use nullable value types, use a <see cref="Nullable{T}"/>
        /// variant type.
        /// </summary>
        public virtual bool IsNullable { get; set; }
        
        /// <summary>
        /// Gets or sets a value indicating whether this variant is the default value of the uninitialized
        /// variant. Only one variant may be the default value.
        /// This setting is only relevant for <see langword="struct"/> union types.
        /// Only variants of a value type or nullable reference type may be designated as default variants.
        /// </summary>
        public virtual bool IsDefault { get; set; }
    }
    
    /// <summary>
    /// Marks the target type as a union type with the variant <typeparamref name="T0"/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    sealed partial class UnionTypeAttribute<T0> : NamedUnionTypeBaseAttribute
    { }
    /// <summary>
    /// Marks the target type as a union type with the variants 
    /// <typeparamref name="T0"/>
    /// and <typeparamref name="T1"/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    sealed partial class UnionTypeAttribute<T0, T1> : UnionTypeBaseAttribute
    { }
    /// <summary>
    /// Marks the target type as a union type with the variants 
    /// <typeparamref name="T0"/>,
    /// <typeparamref name="T1"/>
    /// and <typeparamref name="T2"/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    sealed partial class UnionTypeAttribute<T0, T1, T2> : UnionTypeBaseAttribute
    { }
    /// <summary>
    /// Marks the target type as a union type with the variants 
    /// <typeparamref name="T0"/>,
    /// <typeparamref name="T1"/>,
    /// <typeparamref name="T2"/>
    /// and <typeparamref name="T3"/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    sealed partial class UnionTypeAttribute<T0, T1, T2, T3> : UnionTypeBaseAttribute
    { }
    /// <summary>
    /// Marks the target type as a union type with the variants 
    /// <typeparamref name="T0"/>,
    /// <typeparamref name="T1"/>,
    /// <typeparamref name="T2"/>,
    /// <typeparamref name="T3"/>
    /// and <typeparamref name="T4"/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    sealed partial class UnionTypeAttribute<T0, T1, T2, T3, T4> : UnionTypeBaseAttribute
    { }
    /// <summary>
    /// Marks the target type as a union type with the variants 
    /// <typeparamref name="T0"/>,
    /// <typeparamref name="T1"/>,
    /// <typeparamref name="T2"/>,
    /// <typeparamref name="T3"/>,
    /// <typeparamref name="T4"/>
    /// and <typeparamref name="T5"/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    sealed partial class UnionTypeAttribute<T0, T1, T2, T3, T4, T5> : UnionTypeBaseAttribute
    { }
    /// <summary>
    /// Marks the target type as a union type with the variants 
    /// <typeparamref name="T0"/>,
    /// <typeparamref name="T1"/>,
    /// <typeparamref name="T2"/>,
    /// <typeparamref name="T3"/>,
    /// <typeparamref name="T4"/>,
    /// <typeparamref name="T5"/>
    /// and <typeparamref name="T6"/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    sealed partial class UnionTypeAttribute<T0, T1, T2, T3, T4, T5, T6> : UnionTypeBaseAttribute
    { }
    /// <summary>
    /// Marks the target type as a union type with the variants 
    /// <typeparamref name="T0"/>,
    /// <typeparamref name="T1"/>,
    /// <typeparamref name="T2"/>,
    /// <typeparamref name="T3"/>,
    /// <typeparamref name="T4"/>,
    /// <typeparamref name="T5"/>,
    /// <typeparamref name="T6"/>
    /// and <typeparamref name="T7"/>.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    sealed partial class UnionTypeAttribute<T0, T1, T2, T3, T4, T5, T6, T7> : UnionTypeBaseAttribute
    { }
    /// <summary>
    /// Marks the target type as a union type with one of the variants being the annotated type parameter.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.GenericParameter, AllowMultiple = false, Inherited = false)]
#if RHOMICRO_CODEANALYSIS_JANUS_ANALYZERS
    [global::RhoMicro.CodeAnalysis.IncludeFile]
    [RhoMicro.CodeAnalysis.GenerateFactory(GenerateModelTypeAsStruct = true)]
#endif
    sealed partial class UnionTypeAttribute : NamedUnionTypeBaseAttribute
    { }
}
