<Project Sdk="Microsoft.NET.Sdk">
	<!--AutoUpdateAssemblyName-->

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<developmentDependency>true</developmentDependency>
		<NoPackageAnalysis>true</NoPackageAnalysis>
		<IsRoslynComponent>true</IsRoslynComponent>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>
			Generates types that help with source code generators and analyzers.
		</Description>
		<PackageTags>Source Generator</PackageTags>
	</PropertyGroup>

	<PropertyGroup>
		<DefineConstants>$(DefineConstants);GENERATOR;UTILITYGENERATORS;INCLUDELIBRARYFILES</DefineConstants>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Update="NETStandard.Library" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
		<PackageReference Include="PolySharp" Version="1.15.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="RhoMicro.CodeAnalysis.UtilityGenerators.Dev" Version="*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	
	<ItemGroup>
		<None Remove=".editorconfig"></None>
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
	</ItemGroup>

</Project>
