// SPDX-License-Identifier: MPL-2.0

// SPDX-License-Identifier: MPL-2.0

namespace RhoMicro.CodeAnalysis;

using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

using Microsoft.CodeAnalysis;

using RhoMicro.CodeAnalysis.Library.Models;

/// <summary>
/// Generates static source texts from annotated source files for inclusion in both a generator as well as its target compilation.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FileInclusionGenerator : IIncrementalGenerator
{
    private const String _hintName = "IncludedFiles.g.cs";
    private const String _attributeMetadataName = "RhoMicro.CodeAnalysis.IncludeFileAttribute";

    private static readonly Regex _rawStringLiteralBraces = new("({|})*", RegexOptions.Compiled);
    private static readonly Regex _rawStringLiteralQuotes = new("(\"*)", RegexOptions.Compiled);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            _attributeMetadataName,
            static (_, _) => true,
            static (ctx, ct) =>
            {
                ct.ThrowIfCancellationRequested();

                var sourceText = ctx.TargetNode.SyntaxTree.ToString();

                using var modelCtx = ModelCreationContext.CreateDefault(ct);

                var hintName = ctx.Attributes[0].NamedArguments.FirstOrDefault(a => a.Key == "Hint").Value.Value?.ToString()
                    ?? ( ctx.TargetSymbol is INamedTypeSymbol target
                        ? NamedTypeModel.Create(target, in modelCtx).GetHintName(ct)
                        : null );

                var result = (sourceText, hintName);

                return result;
            })
            .Select(static (t, ct) =>
            {
                ct.ThrowIfCancellationRequested();

                var hintName = t.hintName ?? $"IncludedSource_{Hash(t.sourceText, ct)}.g.cs";
                var sourceText = t.sourceText;

                var rawDollarsCount = _rawStringLiteralBraces.Matches(sourceText)
                    .Cast<Match>()
                    .Select(m => m.Length)
                    .Append(1)
                    .Max() + 1;
                var rawQuotesCount = _rawStringLiteralQuotes.Matches(sourceText)
                    .Cast<Match>()
                    .Select(m => m.Length)
                    .Append(2)
                    .Max() + 1;

                return (rawDollarsCount, rawQuotesCount, sourceText, hintName);
            })
            .Select(static (t, ct) =>
            {
                var (rawDollarsCount, rawQuotesCount, sourceText, hintName) = t;

                var rawDollars = new String('$', rawDollarsCount);
                var rawBracesOpen = new String('{', rawDollarsCount);
                var rawBracesClose = new String('}', rawDollarsCount);
                var rawQuotes = new String('"', rawQuotesCount);

                var addSourceStatement =
                $$"""
                c.AddSource(
                    "{{hintName}}",
                {{rawDollars}}{{rawQuotes}}
                // <auto-generated>
                // This file was generated by RhoMicro.CodeAnalysis.FileInclusionGenerator.
                // </auto-generated>
                #pragma warning disable
                {{sourceText}}
                {{rawQuotes}});
                """;

                return addSourceStatement;
            })
            .Collect()
            .Select(static (addSourceStatements, ct) =>
            {
                var builder = new StringBuilder(
                    $$"""
                    // <auto-generated>
                    // This file was generated by the RhoMicro.CodeAnalysis.FileInclusionGenerator.
                    // </auto-generated>
                    using Microsoft.CodeAnalysis;
                    using System;

                    namespace RhoMicro.CodeAnalysis.Generated
                    {
                        internal static class IncludedFileSources
                        {
                            public static void RegisterToContext(IncrementalGeneratorInitializationContext context)
                            {
                    """);

                if(addSourceStatements.Length > 0)
                {
                    _ = builder.Append(
                    """
                    
                                context.RegisterPostInitializationOutput(c =>
                                {
                    """);
                }

                foreach(var addSourceStatement in addSourceStatements)
                {
                    _ = builder.AppendLine(addSourceStatement);
                }

                if(addSourceStatements.Length > 0)
                {
                    _ = builder.Append(
                    """
                                });
                    """);
                }

                var result = builder.Append(
                    """
                            }
                        }
                    }
                    """).ToString();

                return result;
            });

        context.RegisterSourceOutput(sourceProvider, (ctx, sourceText) => ctx.AddSource(_hintName, sourceText));
#if RHOMICRO_CODEANALYSIS_UTILITYGENERATORS
        Generated.IncludedFileSources.RegisterToContext(context);
#endif
    }

    private static String Hash(String sourceText, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        using var ms = new MemoryStream();
        new StreamWriter(ms).Write(sourceText);
        ms.Position = 0;
        ct.ThrowIfCancellationRequested();
        var digest = SHA512.Create().ComputeHash(ms);
        ct.ThrowIfCancellationRequested();
        var result = Convert.ToBase64String(digest);

        return result;
    }
}
