// SPDX-License-Identifier: MPL-2.0
// <auto-generated>
// This file was generated using the global::RhoMicro.CodeAnalysis.Lyra.CSharpSourceBuilder.
// </auto-generated>
namespace SampleNamespace
{
    partial class IntDoubleString
    {
        [global::System.FlagsAttribute]
        public enum VariantGroups
        {
            None = 0,
            Integer = 1 << 0,
            Number = 1 << 1,
            ReferenceType = 1 << 2,
            ValueType = 1 << 3
        }
    }
}
namespace SampleNamespace
{
    partial class IntDoubleString
    {
        [global::System.FlagsAttribute]
        public enum VariantGroups
        {
            Double = 0,
            Int32 = 1,
            String = 2
        }
    }
}
