// See https://aka.ms/new-console-template for more information

using System.Collections.Immutable;
using System.ComponentModel;
using System.Net.Http.Headers;
using System.Runtime.InteropServices;
using RhoMicro.CodeAnalysis;
using RhoMicro.CodeAnalysis.Lyra;
using static RhoMicro.CodeAnalysis.Lyra.ComponentFactory;
using Type = System.Type;

// var ids = IntDoubleString.Create(32);
// Console.WriteLine(ids.Variant);
// Console.WriteLine(ids.Value);
// var id = IntDouble.Create(ids);
// Console.WriteLine(id.Variant);
// Console.WriteLine(id.Value);
// id = 42d;
// Console.WriteLine(id.Variant);
// Console.WriteLine(id.Value);
// ids = "Foo";
// Console.WriteLine(ids.Variant);
// Console.WriteLine(ids.Value);

using var sb1 = new CSharpSourceBuilder(
        new CSharpSourceBuilderOptions()
        {
                Prelude = (b,_)=>b.AppendLine("// <auto-generated/>"),
                DefaultIndentation = "  ".AsMemory()
        });
sb1.Append("namespace ").AppendLine("Foo").AppendLine('{');
sb1.Indent();
sb1.Append(
        ComponentFactory.Type(
                "enum",
                "Bar",
                ComponentFactory.Create((b, _) => b.AppendLine("Baz = 0"))));
sb1.Detent();
sb1.AppendLine('}');
Console.WriteLine(sb1);

var placeholder = "\nbar\nbaz";
sb1.Clear().AppendLine(
         $"""
             foo{placeholder}
         """);
Console.WriteLine(sb1);


var variants = new VariantModel[3]
{
        new("Double", 0, new VariantGroupModel[2]), new("Int32", 1, new VariantGroupModel[3]),
        new("String", 2, new VariantGroupModel[1])
};
var groups = new VariantGroupModel[5]
{
        new("None", 0, []), new("Integer", 1, [variants[1]]), new("Number", 2, [variants[0], variants[1]]),
        new("ReferenceType", 3, [variants[2]]), new("ValueType", 4, [variants[0], variants[1]])
};

variants[0].Groups![0] = groups[2];
variants[0].Groups![1] = groups[4];

variants[1].Groups![0] = groups[1];
variants[1].Groups![1] = groups[2];
variants[1].Groups![2] = groups[4];

variants[2].Groups![0] = groups[3];


var model = new UnionModel(
        "class",
        "IntDoubleString",
        "SampleNamespace",
        [new ContainingTypeModel("class", "ContainingType")],
        ImmutableCollectionsMarshal.AsImmutableArray(variants),
        ImmutableCollectionsMarshal.AsImmutableArray(groups));

using var sb = new CSharpSourceBuilder(new CSharpSourceBuilderOptions()
{
        Prelude = (b, _) => b
                            .SetInterpolationIndentationDetector(
                                    NullInterpolationIndentationDetector.Instance,
                                    out var previous)
                            .AppendLine(
                                    $"""
                                     // SPDX-License-Identifier: MPL-2.0
                                     // <auto-generated>
                                     // This file was generated using the {typeof(CSharpSourceBuilder)}.
                                     // </auto-generated>
                                     """)
                            .SetInterpolationIndentationDetector(previous)
});


sb.Append(new VariantGroupKindsComponent(model));
sb.Append(new VariantKindsComponent(model));

File.WriteAllText(Path.Combine(Environment.CurrentDirectory, "../../../", "Output.g.cs"), sb.ToString());

readonly record struct VariantGroupKindsComponent(UnionModel Model) : ICSharpSourceComponent
{
    public void AppendTo(CSharpSourceBuilder builder, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var component = Namespace(
                Model.Namespace,
                Type(
                        $"partial {Model.Modifier}",
                        name: Model.Name,
                        body: Type(
                                modifiers: "public enum",
                                name: "VariantGroups",
                                attributes:
                                [
                                        Attribute(TypeName(typeof(FlagsAttribute)), arguments: [])
                                ],
                                body: List(
                                        Model.VariantGroups,
                                        static (v, i, l, b, ct) =>
                                        {
                                            ct.ThrowIfCancellationRequested();

                                            if (i is 0)
                                            {
                                                b.Append($"{v.Name} = 0");
                                            }
                                            else
                                            {
                                                b.Append($"{v.Name} = 1 << {i - 1}");
                                            }
                                        },
                                        separator: ",\n",
                                        terminator: "\n"))));

        builder.Append(component);
    }
}

readonly record struct VariantKindsComponent(UnionModel Model) : ICSharpSourceComponent
{
    public void AppendTo(CSharpSourceBuilder builder, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var component = Namespace(
                Model.Namespace,
                Type(
                        modifiers: $"partial {Model.Modifier}",
                        name: Model.Name,
                        body: Type(
                                modifiers: "public enum",
                                name: "VariantGroups",
                                attributes:
                                [
                                        Attribute(TypeName(typeof(FlagsAttribute)), arguments: [])
                                ],
                                body: List(
                                        Model.Variants,
                                        static (v, i, l, b, ct) =>
                                        {
                                            ct.ThrowIfCancellationRequested();

                                            b.Append($"{v.Name} = {i}");
                                        },
                                        separator: ",\n",
                                        terminator: "\n"))));

        builder.Append(component);
    }
}


readonly record struct VariantModel(String Name, Int32 Index, VariantGroupModel[] Groups);

readonly record struct VariantGroupModel(String Name, Int32 Index, VariantModel[] Variants);

readonly record struct ContainingTypeModel(String Modifier, String Name);

sealed record UnionModel(
        String Modifier,
        String Name,
        String Namespace,
        ImmutableArray<ContainingTypeModel> ContainingTypes,
        ImmutableArray<VariantModel> Variants,
        ImmutableArray<VariantGroupModel> VariantGroups);

// ###############
// generated below
// ###############
