<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<AssemblyName Condition="'$(SolutionName)'!=''">$(SolutionName).$(MSBuildProjectName)</AssemblyName>

		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
		<RootNamespace Condition="'$(SolutionName)'!=''">$(SolutionName).$(MSBuildProjectName.Replace(".", "_"))</RootNamespace>

		<WarningsAsErrors>$(WarningsAsErrors);NU1605;1591;1573;1712;nullable</WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="..\UtilityGenerators\Templating\CodeSyntaxModel.cs" Link="CodeSyntaxModel.cs" />
	  <Compile Include="..\UtilityGenerators\Templating\SourceSpanModel.cs" Link="SourceSpanModel.cs" />
	  <Compile Include="..\UtilityGenerators\Templating\SyntaxKind.cs" Link="SyntaxKind.cs" />
	  <Compile Include="..\UtilityGenerators\Templating\TemplateChildSyntaxModel.cs" Link="TemplateChildSyntaxModel.cs" />
	  <Compile Include="..\UtilityGenerators\Templating\TemplateSyntaxBaseModel.cs" Link="TemplateSyntaxBaseModel.cs" />
	  <Compile Include="..\UtilityGenerators\Templating\TemplateSyntaxModel.cs" Link="TemplateSyntaxModel.cs" />
	  <Compile Include="..\UtilityGenerators\Templating\TextOrValueSyntaxModel.cs" Link="TextOrValueSyntaxModel.cs" />
	  <Compile Include="..\UtilityGenerators\Templating\TextSyntaxModel.cs" Link="TextSyntaxModel.cs" />
	  <Compile Include="..\UtilityGenerators\Templating\ValueSyntaxModel.cs" Link="ValueSyntaxModel.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
	</ItemGroup>

	<!--<ItemGroup>
	  <PackageReference Include="RhoMicro.CodeAnalysis.UnionsGenerator" Version="14.0.4">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>-->

	<ItemGroup>
		<ProjectReference Include="../UtilityGenerators/UtilityGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>