<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RollForward>major</RollForward>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="..\JsonSchemaGenerator\Attributes\GeneratedJsonSchemaAttribute.cs" Link="GeneratedJsonSchemaAttribute.cs" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="RhoMicro.CodeAnalysis.JsonSchemaGenerator.Tests.1.0.0" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="IKVM.Core.MSBuild" Version="0.1.103">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0" />
		<PackageReference Include="PolySharp" Version="1.15.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
