<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>RhoMicro.CodeAnalysis.DocReflect</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>Provides the types required to inspect type documentation using a reflection-like api.</Description>
		<PackageTags>Source Generator; Documentation; Reflection</PackageTags>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\DictionaryEqualityComparer.cs" Link="DictionaryEqualityComparer.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\EnumerableEqualityComparer.cs" Link="EnumerableEqualityComparer.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\EqualityComparerFactory.cs" Link="EqualityComparerFactory.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\EquatableCollection.cs" Link="EquatableCollection.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\EquatableCollectionFactory.cs" Link="EquatableCollectionFactory.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\EquatableDictionary.cs" Link="EquatableDictionary.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\EquatableList.cs" Link="EquatableList.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\EquatableSet.cs" Link="EquatableSet.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\KeyValuePairEqualityComparer.cs" Link="KeyValuePairEqualityComparer.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\LazyEquatableDictionary.cs" Link="LazyEquatableDictionary.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\LazyEquatableList.cs" Link="LazyEquatableList.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\MutabilityContext.cs" Link="MutabilityContext.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\MutableCollection.cs" Link="MutableCollection.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\Collections\SetEqualityComparer.cs" Link="SetEqualityComparer.cs" />
	  <Compile Include="..\UtilityGenerators\Library\Models\ModelCreationContext.cs" Link="ModelCreationContext.cs" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
		<PackageReference Include="PolySharp" Version="1.15.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
	</ItemGroup>
	
</Project>